import { Poppins } from "next/font/google";
import 'bootstrap-icons/font/bootstrap-icons.css'
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"],weight:'400' });

export const metadata = {
  title: "Twitter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-[60%] mx-auto my-0 flex justify-between ${poppins.className}`}>
        {children}
        </body>
    </html>
  );
}