import { Inter } from "next/font/google";
import AsideLinks from "./aside";
import News from "./news";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Twitter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-11/12 mx-auto my-0 flex justify-between">
        <AsideLinks/>
        {children}
        <News/>
        </body>
    </html>
  );
}
